# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: db3aded543437850862c56ebecc3201e12688b69596efcca7120bf5d10704ff2eec75d8187af38782f65dedde6b125c8eb44a85b34b23d594d323cfc37846166

test:
  secret_key_base: eee8040e081aaf3a669523d1405cf2af9d1a419f606174791b9f48564c7c1d272a7e842680d52979dd2e2507278dd7184c756c237854f687ceb551e396066599

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
